/**
 * Mirror of packages/contracts/src/errors.ts. Kept in-tree so the API can
 * import these types without a workspace path mapping (api/tsconfig.json does
 * not configure paths and api/package.json does not depend on @yinjie/contracts;
 * see api/src/modules/admin/wiki-sync.types.ts for the same pattern).
 *
 * Update both files when adding a new error code.
 */
export type KnownAppErrorCode =
  | 'LEGACY_ERROR'
  | 'INTERNAL_ERROR'
  | 'VALIDATION_FAILED'
  | 'FARM_CHARACTER_REQUIRED'
  | 'FARM_INVALID_PLOT_INDEX'
  | 'FARM_UNKNOWN_CROP'
  | 'FARM_CHARACTER_NOT_PARTICIPATING'
  | 'FARM_CHARACTER_NOT_FOUND'
  | 'FARM_CHARACTER_NOT_VISIBLE'
  | 'FARM_LEVEL_TOO_LOW'
  | 'FARM_BUY_LEVEL_TOO_LOW'
  | 'FARM_INSUFFICIENT_COINS'
  | 'FARM_PLOT_NOT_FOUND'
  | 'FARM_PLOT_NOT_PLANTABLE'
  | 'FARM_PLOT_EMPTY'
  | 'FARM_CROP_NOT_RIPE'
  | 'FARM_NPC_OPERATION_NOT_OPEN'
  | 'FARM_QUANTITY_INVALID'
  | 'FARM_WAREHOUSE_INSUFFICIENT'
  | 'FARM_NPC_NO_FARM'
  | 'FARM_ALREADY_STOLEN'
  | 'FARM_ALREADY_WATERED'
  | 'FARM_NO_WEEDS'
  | 'FARM_NO_BUGS'
  | 'FARM_DAILY_STEAL_LIMIT'
  | 'MOMENTS_MEDIA_REQUIRED'
  | 'MOMENTS_INVALID_MEDIA_TYPE'
  | 'MOMENTS_MEDIA_NOT_FOUND'
  | 'MOMENTS_NOT_FOUND'
  | 'MOMENTS_NOT_FRIEND'
  | 'MOMENTS_EMPTY'
  | 'MOMENTS_TEXT_NO_MEDIA'
  | 'MOMENTS_VIDEO_SINGLE'
  | 'MOMENTS_VIDEO_TOO_LONG'
  | 'MOMENTS_IMAGES_MAX'
  | 'MOMENTS_IMAGES_TYPE_ONLY'
  | 'REMINDER_LIMIT_INVALID'
  | 'REMINDER_ONLY_ACTIVE_COMPLETE'
  | 'REMINDER_ONLY_ACTIVE_DEFER'
  | 'REMINDER_NOT_FOUND'
  | 'REMINDER_UNTIL_INVALID'
  | 'REMINDER_DEFER_INVALID'
  | 'CHARACTER_NOT_FOUND'
  | 'CHARACTER_ALREADY_EXISTS'
  | 'CHARACTER_DEFAULT_NOT_DELETABLE'
  | 'PRESET_NOT_FOUND'
  | 'PRESET_AT_LEAST_ONE'
  | 'BLUEPRINT_CHAT_SAMPLE_REQUIRED'
  | 'BLUEPRINT_REVISION_NOT_FOUND'
  | 'SHAKE_DISABLED'
  | 'SHAKE_COOLDOWN'
  | 'SHAKE_DAILY_LIMIT'
  | 'SHAKE_CYBER_AVATAR_NO_SIGNAL'
  | 'SHAKE_SESSION_NOT_FOUND'
  | 'SHAKE_NOT_DISCARDABLE'
  | 'SHAKE_KEPT_CHARACTER_MISSING'
  | 'SHAKE_NOT_KEEPABLE'
  | 'SHAKE_DRAFT_MISSING'
  | 'SHAKE_CHARACTER_CREATE_FAILED'
  | 'SHAKE_NO_DIRECTIONS'
  | 'AUTH_USERNAME_PASSWORD_REQUIRED'
  | 'AUTH_USERNAME_TAKEN'
  | 'AUTH_INVALID_CREDENTIALS'
  | 'AUTH_EMAIL_LOGIN_ONLY'
  | 'AUTH_JWT_SECRET_MISSING'
  | 'AUTH_CODE_REQUIRED'
  | 'AUTH_CODE_INVALID'
  | 'AUTH_CODE_USED'
  | 'AUTH_CODE_EXPIRED'
  | 'AUTH_EMAIL_INVALID'
  | 'AUTH_TOKEN_MISSING'
  | 'AUTH_TOKEN_INVALID'
  | 'AUTH_USER_NOT_FOUND'
  | 'AUTH_EMAIL_BIND_FAILED'
  | 'AUTH_EMAIL_SEND_FAILED'
  | 'AUTH_CODE_RESEND_TOO_FAST'
  | 'AUTH_CODE_TOO_MANY'
  | 'AI_AUDIO_REQUIRED'
  | 'AI_AUDIO_MODE_UNSUPPORTED'
  | 'AI_TTS_TEXT_REQUIRED'
  | 'AI_TTS_EMPTY'
  | 'AI_AUDIO_RETRY_FAILED'
  | 'AI_RATE_LIMIT'
  | 'AI_PROVIDER_UNAVAILABLE'
  | 'AI_IMAGE_PROMPT_REQUIRED'
  | 'AI_IMAGE_EMPTY'
  | 'AI_IMAGE_PROVIDER_UNAVAILABLE'
  | 'AI_TRANSCRIBE_AUDIO_REQUIRED'
  | 'AI_TRANSCRIBE_TOO_LARGE'
  | 'AI_TRANSCRIBE_FORMAT_INVALID'
  | 'AI_TRANSCRIBE_PROVIDER_UNAVAILABLE'
  | 'AI_TRANSCRIBE_GATEWAY_FAILED'
  | 'AI_SPEECH_ASSET_NOT_FOUND';

export type AppErrorCode = KnownAppErrorCode | (string & {});

export type AppErrorParams = Record<string, string | number | boolean | null>;

export interface AppErrorBody {
  code: AppErrorCode;
  params?: AppErrorParams;
  legacyMessage?: string;
  statusCode?: number;
  message?: string | string[];
  error?: string;
  requestId?: string | null;
  meta?: unknown;
}
